name: gmapy-conda-env
dependencies:
  - python=3.9
  - numpy=1.23
  - pandas=1.4
  - scipy=1.9
  - pip=22.2
  - suitesparse
  - pip:
    - fortranformat==1.2.2
    - scikit-sparse==0.4.12
    - tensorflow==2.13
    - tensorflow_probability==0.21.0
    - dill==0.3.7
